### ISSUE TITLE
Unsafe use of eval

### ISSUE THREAD

**Issue by cristianstaicu** [notduncansmith/summit#23]
The following use of eval in lib/drivers/search/pouch.js is dangerous:

``` js
if (typeof opts.collection === 'string') {
        opts.filter = "function filter (doc) {return doc.type === '" + opts.collection + "'}";
      }
      else {
        opts.filter =  "function filter (doc) {";

        opts.filter += opts.collection.map(function (c) {
          return "if (doc.type === '" + c + "') {return true;}";
        }).join('\n');

        opts.filter += "return false;}";
      }
      eval(opts.filter);
```

An attacker can use a malicious payload instead of a valid collection name to inject arbitrary commands. I suggest one of the following options: refactoring out eval, use adhoc regex validation or use a heavyweight sanitization package like
https://www.npmjs.com/package/eval-sanitizer

**Comment by notduncansmith** [comment]
Hey Cristian, thanks for the report, and self-promotion tip. Will get on this soon. In the meantime, PouchDB is not the recommended driver for production.

**Comment by notduncansmith** [comment]
Just came back to this and remembered that PouchDB's search driver is unfinished. Closing this for now.
